### ISSUE TITLE
look over the draft?

### ISSUE THREAD

**Issue by cboettig** [rocker-org/rocker-paper#1]
Hi @eddelbuettel ,

Okay, I think I have a reasonable draft ready, [pdf here](https://github.com/rocker-org/rocker-paper/blob/master/RJwrapper.pdf).  Let me know when you get a chance to look over it; and feel free to push edits or comments directly to the [manuscript.Rmd](https://github.com/rocker-org/rocker-paper/blob/master/manuscript.Rmd) as you've done before.  Thanks! Looking forward to having this out at last.

**Comment by eddelbuettel** [comment]
Will do this weekend!  And agreed, we should push this can down the road.  Thanks for re-igning this.
