### ISSUE TITLE
feedback on draft

### ISSUE THREAD

**Issue by nuest** [rocker-org/rocker-paper#2]
First of all, I really enjoyed reading the paper. I've worked quite a bit with the Rocker images, but learned some new stuff and the whole story certainly should make the project easier to grasp for newcomers. I also like the level of detail you have. So, here are some comments:

(I use the blame links in the following to be able to [link to lines within the Markdown doc](https://github.com/holman/ama/issues/305), not to... blame.)

- [x] [... download time, and are built ..., and provide...](https://github.com/rocker-org/rocker-paper/blame/5da4641de873784304f00027d03adda997cbe55c/manuscript.Rmd#L49) - remove "and" in second to last list item
- [x] Suggest to add a couple of sentences about Dockerfiles, containers vs. images, and "image stacks" to [What is Docker?](https://github.com/rocker-org/rocker-paper/blame/5da4641de873784304f00027d03adda997cbe55c/manuscript.Rmd#L41), as these terms might be unknown to readers but understanding is important for getting the argument in the upcoming paragraphs. "A Docker image is build from a Dockerfile, a human and machine-readable recipe. A Dockerfile can build upon an existing image creating a stack of images." If you intentionally don't want to open the "containers vs. images" thing for simplicity, ignore this comment.
- [x] ["issue tracker" beats "issues tracker" on Google search](https://github.com/rocker-org/rocker-paper/blame/5da4641de873784304f00027d03adda997cbe55c/manuscript.Rmd#L61)
- [x] [.. defined by which Debian distribution ..](https://github.com/rocker-org/rocker-paper/blame/5da4641de873784304f00027d03adda997cbe55c/manuscript.Rmd#L96) - In my understanding of the word "define", I would say it's the other way around: the needs {are matched by/are represented by/are supported by} the base distribution.
- [x] [Debian stable](https://github.com/rocker-org/rocker-paper/blame/5da4641de873784304f00027d03adda997cbe55c/manuscript.Rmd#L98) - to me it is unclear why this is not `debian:stable`. Maybe add an example if you want refer to specific stable releases: "Debian stable releases (e.g. `debian:jessie`). Because the image `debian:stable` exists and is a rolling tag just as `debian:testing`.
- [ ] [apt-pinning vs. `debian:unstable`](https://github.com/rocker-org/rocker-paper/blame/5da4641de873784304f00027d03adda997cbe55c/manuscript.Rmd#L113-L114) - Why use apt-pinning and `testing`, instead of just going with `unstable` ?
- [x] [ "a the package"](https://github.com/rocker-org/rocker-paper/blame/5da4641de873784304f00027d03adda997cbe55c/manuscript.Rmd#L132) - probably "a package"
- [x] ["Box 1" seems to be gone](https://github.com/rocker-org/rocker-paper/blame/5da4641de873784304f00027d03adda997cbe55c/manuscript.Rmd#L134)
- [x] [`docker pull` in examples](https://github.com/rocker-org/rocker-paper/blame/5da4641de873784304f00027d03adda997cbe55c/manuscript.Rmd#L165) - for readers completely new to Docker, the example could use `docker run ...` instead of `pull`, because that's also used in later examples and "running a container" might need no explanation, while "pulling an image" might. Just a thought.
- [x] [this stack does include many specific R packages](https://github.com/rocker-org/rocker-paper/blame/5da4641de873784304f00027d03adda997cbe55c/manuscript.Rmd#L182-L183) - should it not be _"this stack does not include many..."_ ?
- [each week](https://github.com/rocker-org/rocker-paper/blame/5da4641de873784304f00027d03adda997cbe55c/manuscript.Rmd#L205) vs. [almost daily](https://github.com/rocker-org/rocker-paper/blame/5da4641de873784304f00027d03adda997cbe55c/manuscript.Rmd#L212) - used phrases not contradictory, but could be the same nevertheless.
- [x] [on the download numbers](https://github.com/rocker-org/rocker-paper/blame/5da4641de873784304f00027d03adda997cbe55c/manuscript.Rmd#L208) - as of when? I guess you plan to update the numbers closer to the publication date, https://hub.docker.com/v2/repositories/library/r-base/ now well over 620000. :100: 
- [ ] [built from separate Dockerfiles](https://github.com/rocker-org/rocker-paper/blame/5da4641de873784304f00027d03adda997cbe55c/manuscript.Rmd#L263) - you could mention here that in addition version have their own Dockerfiles, and briefly describe the directory structure of https://github.com/rocker-org/rocker-versioned/ ... it could encourage readers to actually take a look at the Dockerfiles. In that direction, have you considered putting a complete Dockerfile in the paper for illustration?
- [ ] [MRAN only going back to `3.1`](https://github.com/rocker-org/rocker-paper/blame/5da4641de873784304f00027d03adda997cbe55c/manuscript.Rmd#L262) - would it be possible to manually create a snapshot using the CRAN archives? Would like to know if you've done some work here, because we've recently tried to reproduce papers older than 2014 and ran into troubles. I digress.
- [x] [Why is the switch to `stretch` made with `3.4.0`, and not for another version?](https://github.com/rocker-org/rocker-paper/blame/5da4641de873784304f00027d03adda997cbe55c/manuscript.Rmd#L275) - this could be as simple as mentioning the release date of `3.4.0`.
- [x] [Docker install code](https://github.com/rocker-org/rocker-paper/blame/5da4641de873784304f00027d03adda997cbe55c/manuscript.Rmd#L453) - maybe say "bash code" or shell code, or start the example with `$`,
- [x] ["... RStudio's default `:8787` ..."](https://github.com/rocker-org/rocker-paper/blame/5da4641de873784304f00027d03adda997cbe55c/manuscript.Rmd#L463) - suggest to leave out the `:`, or you'll have to explain the `-p` optionhttps://github.com/rocker-org/rocker-paper/blame/5da4641de873784304f00027d03adda997cbe55c/manuscript.Rmd#L491-L493
- [x] RStudio _with trademark_ is used [here](https://github.com/rocker-org/rocker-paper/blame/5da4641de873784304f00027d03adda997cbe55c/manuscript.Rmd#L486) but not on page 3, suggest to harmonize
- [x] [permission](https://github.com/rocker-org/rocker-paper/blame/5da4641de873784304f00027d03adda997cbe55c/manuscript.Rmd#L491-L493) already mentioned earlier, can probably be left out; also "_Some_ rocker images include the RStudio-server software..."?
- [x] [".. in an instance running the container .."]() - for users not knowing `docker exec` this might be confusing (instance/container/host), maybe "Users of the `rstudio` images can access a root `bash` shell in a running container using the command `docker exec...` on the host computer. This can be useful..."
- [x] Maybe consider `container` instead of `instance` (several locations in the text) ?
- [R, RScript, or bash](https://github.com/rocker-org/rocker-paper/blame/5da4641de873784304f00027d03adda997cbe55c/manuscript.Rmd#L503) vs. [`R`, `RScript`, or `bash`](https://github.com/rocker-org/rocker-paper/blame/5da4641de873784304f00027d03adda997cbe55c/manuscript.Rmd#L510) - maybe this is intentional because of CLI example or not, but this paragraph seems a bit redundant.
- [x] ["_D_ocker instance"](https://github.com/rocker-org/rocker-paper/blame/5da4641de873784304f00027d03adda997cbe55c/manuscript.Rmd#L507)
- [x] [" Rocker instances offer an easy solution. For instance, a"](https://github.com/rocker-org/rocker-paper/blame/5da4641de873784304f00027d03adda997cbe55c/manuscript.Rmd#L530) - [ ] at least for me as a non-native speaker this repeated usage of "instance" seems weird, suggestion: "Rocker offers and easy solution. For instance, ..."
- [x] Regarding **sandboxing** and [root users installing software in a container](https://github.com/rocker-org/rocker-paper/blame/5da4641de873784304f00027d03adda997cbe55c/manuscript.Rmd#L545), you mean root privileges _inside_ the container, right? Maybe mention that even RStudio users via a browser can install packages (without root access to the container).
- [x] [DockerHub](https://github.com/rocker-org/rocker-paper/blame/5da4641de873784304f00027d03adda997cbe55c/manuscript.Rmd#L556) > Docker Hub
- [x] [.. and discussing these issues which are often overlooked elsewhere. Issues and Pull Requests ...](https://github.com/rocker-org/rocker-paper/blame/5da4641de873784304f00027d03adda997cbe55c/manuscript.Rmd#L577) - Suggestion: _"... and discussing these decisions/choices which are ...", to distinguish GH issues from the optimization challenges.
- [x] Regarding **versions**: I would really love to see a mentioning for the semantic version labels here as an intermediate between "latest" and fully fixed version.
- [x] [R-hub vs. rhub](https://github.com/rocker-org/rocker-paper/blame/5da4641de873784304f00027d03adda997cbe55c/manuscript.Rmd#L652) - `rhub` seems to be the [name for the R package](https://github.com/r-hub/rhub) and "R-hub" for [the project](https://github.com/r-hub), though the latter is not consistent even in the project descriptions on GitHub (also r-hub is used for the project).

Some general comments:

- Cool new website by the way!
- Sadly I do not have a good source to cite for this, but all presentations at useR!2017 on "real-world large scale Shiny deployments" mentioned using Docker. It might be worth reviewing those talks to make the case even stronger with **production use of Rocker images**.

**Comment by eddelbuettel** [comment]
Wow. Thanks so much, Daniel!  That's thorough with a capital T.

**Comment by cboettig** [comment]
All integrated, closing out.
